const data=[
    {
        id:1,
        name:"Dr.Tomas",
        specialist:"heart",
        img:"https://s3-eu-west-1.amazonaws.com/intercare-web-public/wysiwyg-uploads%2F1569586526901-doctor.jpg",
        email:'tms@gmail.com'
    },
    {
        id:2,
        name:"Dr.borner",
        specialist:"heartSpecilist",
        img:"https://previews.123rf.com/images/pitinan/pitinan1706/pitinan170600082/80545152-male-doctor-in-the-hospital-or-doctor-office-concept-of-medical-technology-and-doctor-career-.jpg",
        email:'borner67@gmail.com'
    },
    {
        id:3,
        name:"Dr.aniin",
        specialist:"childSpecilist",
        img:"https://media.istockphoto.com/photos/portrait-of-middle-aged-asian-female-doctor-standing-in-hospital-picture-id1271328839?b=1&k=20&m=1271328839&s=170667a&w=0&h=SIMzwoe8eu43OoY4M3ElZCMxW9MgDbZbVzMhh4VY2zM=",
        email:'anin@gmail.com'
    },
    {
        id:4,
        name:"Dr.shushiya",
        specialist:"heartSpecilist",
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJlj3AS3gczyyMRlmoRH84lfCgo2MhY7n3uQ&usqp=CAU",
        email:'shushiyaZa@gmail.com'
    },
    {
        id:5,
        name:"Dr.Young",
        specialist:"heartSpecilist",
        img:"https://yt3.ggpht.com/ytc/AKedOLSKtGMWDQ43_1SKX53sKoIFBotUtJqi4wL-GUTkWA=s900-c-k-c0x00ffffff-no-rj",
        email:'Young67@gmail.com'
    },
    {
        id:6,
        name:"Dr.patric",
        specialist:"heartSpecialis",
        img:"https://image.shutterstock.com/image-photo/doctor-senior-man-medical-professional-260nw-1077126038.jpg",
        email:'patric@gmail.com'
    },
    {
        id:7,
        name:"Dr.David",
        specialist:"heartSpecialist",
        img:"https://img.freepik.com/free-photo/portrait-smiling-handsome-male-doctor-man_171337-5055.jpg?size=626&ext=jpg",
        email:'david1@gmail.com'
    },
    {
        id:8,
        name:"Dr.Miller",
        specialist:"childSpecialist",
        img:"https://t4.ftcdn.net/jpg/02/60/04/09/360_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg",
        email:'miller!23@gmail.com'
    },
];
export default data;